### ISSUE TITLE
HTML Validation

### ISSUE THREAD

**Issue by acushlakoncept** [gblessylva/JavaScript-Games#2]
**The is really amazing project, great job 👏** 

As an aspiring developer, it's a good practice to imbibe good HTML practices.
Let the HTML validator site: https://validator.w3.org/#validate-by-upload be always there by your side to use in validating all you HTML semantics to be sure you are on track.

Your main index.html contains about 2 HTML errors.
Your epele contains about 6 HTML errors and 2 warnings.
Your conwal index.html contains about 1 HTML errors.

Use the HTML validator to fix the errors.

Happy Coding 👍

**Comment by gblessylva** [comment]
ISSUE FIXED
